import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "../globals.css";
import SupabaseProvider from "@/lib/supabase/SupabaseProvider";
import { Toaster } from "@/components/ui/sonner";

import { NextIntlClientProvider } from "next-intl";
import { esES, ptBR, enUS } from "@clerk/localizations";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }
  const clerkLocale = locale === "pt" ? ptBR : enUS;
  const messages = await getMessages();

  return (
    <ClerkProvider
      signInUrl={`/${locale}/sign-in`}
      signUpUrl={`/${locale}/sign-up`}
      localization={clerkLocale}
    >
      <html
        lang={locale}
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className={`${geistSans.className} min-h-full flex flex-col`}>
          <NextIntlClientProvider messages={messages as any}>
            <SupabaseProvider>{children}</SupabaseProvider>
          </NextIntlClientProvider>

          <Toaster
            position="bottom-right"
            toastOptions={{
              classNames: {
                toast:
                  "bg-white border border-slate-200 shadow-md text-slate-800",
                error: "border-red-200 bg-red-50 text-red-800",
                success: "border-green-200 bg-green-50 text-green-800",
                description: "text-slate-500",
              },
            }}
          />
        </body>
      </html>
    </ClerkProvider>
  );
}
